/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 * Author:  AKA
 * Created: Aug 26, 2016
 */

--------------------------------------------------------
--  DDL for dropping tables
--------------------------------------------------------

  DROP TABLE PERSON;
  DROP TABLE MEMBER;
  DROP TABLE VOICE;



CREATE TABLE PERSON
  (     PERSONID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
  		FIRSTNAME VARCHAR(30) PRIMARY KEY,
        LASTNAME VARCHAR(30),
        BIRTHDATE DATE
  );

CREATE TABLE MEMBER
  (     PERSONID INT, 
  		VOICEID INT,
  		PHONE VARCHAR(30),
        EMAIL VARCHAR(30)
  );

CREATE TABLE VOICE
  (     VOICEID INT NOT NULL GENERATED BY DEFAULT AS IDENTITY, 
  		NAME VARCHAR(30)
  );


ALTER TABLE VOICE ADD CONSTRAINT PK_VOICE PRIMARY KEY (VOICEID);
ALTER TABLE MEMBER ADD CONSTRAINT FK_MEMBER FOREIGN KEY (VOICEID) REFERENCES VOICE (VOICEID);
